### ISSUE TITLE
MemoryCache Prop Orientation

### ISSUE THREAD

**Issue by Kavex** [ZettaiVR/CVR-Mods#3]
I noticed this mod causes props to spawn in the orginal model's orientation and not the set orientation. I tested this with several props and they all seem to have that issue. 

https://imgur.com/a/3vOyFt7

You can try it using the public prop: Kiddy Pool

**Comment by ZettaiVR** [comment]
Please test with the updated file, I'm not sure if I have to reset the position on props or not, I rarely use them.

**Comment by Kavex** [comment]
> Please test with the updated file, I'm not sure if I have to reset the position on props or not, I rarely use them.

Several people can confirmed fixed, good job
