### ISSUE TITLE
[Feature Request] Increase the limit of loadTimeoutSecondsEntry

### ISSUE THREAD

**Issue by kafeijao** [ZettaiVR/CVR-Mods#6]
I have a couple of friends that will start to timeout fetching avatarson worlds with higher player count and a bunch of props enabled. I noticed the loadTimeoutSecondsEntry is a `byte` so the limit is 255 seconds. Maybe this could be increased?

**Comment by ZettaiVR** [comment]
255 seconds is 4.25 minutes, I can switch to short, but this timeout starts after the bundle is downloaded and checked by bundle verifier, and 4 minutes for that should be enough. Also added that 0 disables the timeout entirely.

**Comment by kafeijao** [comment]
Oooh that's a great idea (disabling). Thank you~~~
