### ISSUE TITLE
MemoryCache and video players on props

### ISSUE THREAD

**Issue by racushstrago** [ZettaiVR/CVR-Mods#7]
it seems when I keep memory cache mod active and spawn a prop with a video player attached or even if another play spawns them the video player is removed from the prop.  Prop filter was also set to just show everything fully.

- [02:24:53.593] [MemoryCache] Downloading asset 'Prop': assetId: '924edad7-5eb8-422c-8e20-6b20e044fce8', fileId: '2fef8115da1c', fileHash: 'dbd701d764b8d736654d4349a8785857', fileSize: 8921958, assetUrl empty? False, tags: FlashingColors.
- [02:24:53.593] [MemoryCache] Downloading 'Prop'.
- [02:24:53.772] [MemoryCache] Instantiating asset 'Prop': '924edad7-5eb8-422c-8e20-6b20e044fce8', '2fef8115da1c', 'p+924edad7-5eb8-422c-8e20-6b20e044fce8~490220FA0FEF', tags: FlashingColors.
- [02:24:54.414] [MemoryCache] Added asset 'Prop' with ID '924edad7-5eb8-422c-8e20-6b20e044fce8', file ID '2fef8115da1c', game object name '_CVRSpawnable', tags: FlashingColors.
- [02:24:54.414] [MemoryCache] Instantiating item Prop: ID: '924edad7-5eb8-422c-8e20-6b20e044fce8', fileId: '2fef8115da1c', owner: 'p+924edad7-5eb8-422c-8e20-6b20e044fce8~490220FA0FEF'.
- [02:24:54.414] [MemoryCache] isOwnOrFriend: True, isVisible: True, mustShow: False.
- [02:24:54.415] [MemoryCache] OriginalItem: '_CVRSpawnable', instance: '_CVRSpawnable(Clone)'.v

**Comment by ZettaiVR** [comment]
Fixed in a9f8126

**Comment by racushstrago** [comment]
looking good now with that fix thanks
