### ISSUE TITLE
[BUG] MemCache (May 4, 2023) soft-crashing when trying to download newly un-blocked avatars

### ISSUE THREAD

**Issue by MachMX** [ZettaiVR/CVR-Mods#8]
Issue:
Memory Cache will soft-crash as title indicates.

From here on I will refer **Memory Cache** as _MemC_

Reproduction:
Have an avatar blocked with _MemC_ turned on -most scenarios are avatar download size blocking- and expanding the download size/removing block tag and attempting to re-download the now unblocked avatar will just make the user's avatar completely invisible -no loading hologram even. And in some instances also breaks all new avatar downloads on that instance.

Observations:
As mentioned, its a soft crash, turning OFF the _MemC_ mod and rejoining the instance or joining a new one and enabling _MemC_ will most times unclog it. Also to be able to view back new avatars after this happens, turning OFF _MemC_ and Removing all Avatars and Reloading all of them again will let one see and download avatars again, but with vanilla download routine.

Previous _MemC_ behavior observations:
Previous version to _MemC_ (May 4, 2023) allowed for updating avatar download size blocking and just reloading the specific avatar would download it without issues.

**Comment by ZettaiVR** [comment]
try if it still happens, not sure I've fixed it with the latest release
